"""empty message

Revision ID: 3a7332b8d2f8
Revises: 
Create Date: 2023-12-14 10:35:58.733741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a7332b8d2f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activities_table'))
    )
    op.create_table('campers_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campers_table'))
    )
    op.create_table('signups_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('camper_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities_table.id'], name=op.f('fk_signups_table_activity_id_activities_table')),
    sa.ForeignKeyConstraint(['camper_id'], ['campers_table.id'], name=op.f('fk_signups_table_camper_id_campers_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signups_table'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signups_table')
    op.drop_table('campers_table')
    op.drop_table('activities_table')
    # ### end Alembic commands ###
